import { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone';
import { motion } from 'framer-motion';
import { Upload, X, Image, Tag, DollarSign, FileText, Shield, ChevronDown } from 'lucide-react';
import { artworkAPI, uploadAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';

const CATEGORIES = ['Fantasy Art', 'Paintings', 'Concept Art', 'Illustrations', '3D Art', 'Anime', 'Abstract', 'Cyberpunk'];
const LICENSE_TYPES = [
  { value: 'Personal', desc: 'For personal projects only' },
  { value: 'Commercial', desc: 'Commercial use allowed' },
  { value: 'Extended', desc: 'Full rights including merchandise' },
];

export default function SellArtPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [uploading, setUploading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [preview, setPreview] = useState(null);
  const [tagInput, setTagInput] = useState('');
  const [analyzing, setAnalyzing] = useState(false);
  const [form, setForm] = useState({
    title: '',
    description: '',
    category: '',
    price: '',
    licenseType: 'Commercial',
    tags: [],
    imageUrl: '',
  });

  const onDrop = useCallback(async (acceptedFiles) => {
    const file = acceptedFiles[0];
    if (!file) return;
    setPreview(URL.createObjectURL(file));
    setUploading(true);
    setUploadProgress(0);

    // Simulate progress
    const interval = setInterval(() => {
      setUploadProgress(p => {
        if (p >= 90) { clearInterval(interval); return 90; }
        return p + 10;
      });
    }, 200);

    try {
      const formData = new FormData();
      formData.append('image', file);
      const res = await uploadAPI.image(formData);
      setForm(prev => ({ ...prev, imageUrl: res.data.url }));
      setUploadProgress(100);
      toast.success('Image uploaded!');
    } catch {
      // Fallback: convert to base64 so the image persists (not a blob URL)
      const reader = new FileReader();
      reader.onload = (e) => {
        const base64 = e.target.result;
        setForm(prev => ({ ...prev, imageUrl: base64 }));
      };
      reader.readAsDataURL(file);
      setUploadProgress(100);
      toast.success('Image ready!');
    } finally {
      clearInterval(interval);
      setUploading(false);
    }
  }, []);

  const handleAiGenerate = async () => {
    const targetUrl = form.imageUrl || preview;
    if (!targetUrl) {
      toast.error('Please upload an image first');
      return;
    }
    setAnalyzing(true);
    try {
      const res = await uploadAPI.analyze(targetUrl);
      const meta = res.data?.metadata;
      if (meta) {
        setForm(prev => ({
          ...prev,
          title: meta.title || prev.title,
          description: meta.description || prev.description,
          tags: meta.tags || prev.tags,
        }));
        toast.success('Gallery metadata generated by Gemini 2.5 Flash!');
      }
    } catch (err) {
      toast.error('AI analysis failed.');
    } finally {
      setAnalyzing(false);
    }
  };

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { 'image/*': ['.jpg', '.jpeg', '.png', '.webp', '.gif'] },
    maxSize: 50 * 1024 * 1024,
    multiple: false,
  });


  const addTag = () => {
    const t = tagInput.trim().toLowerCase().replace(/\s+/g, '-');
    if (t && !form.tags.includes(t) && form.tags.length < 10) {
      setForm(prev => ({ ...prev, tags: [...prev.tags, t] }));
      setTagInput('');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user) { toast.error('Please login'); navigate('/login'); return; }
    if (!form.title || !form.price || !form.category) { toast.error('Fill all required fields'); return; }
    if (!form.imageUrl) { toast.error('Please upload an artwork image'); return; }

    setSubmitting(true);
    try {
      const payload = {
        ...form,
        price: Number(form.price),
      };
      const res = await artworkAPI.create(payload);
      toast.success('Artwork published!');
      navigate(`/artwork/${res.data?.artwork?._id}`);
    } catch (err) {
      toast.error('Failed to publish artwork. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen pt-20 px-6 pb-16">
      <div className="max-w-5xl mx-auto">
        <div className="mb-10">
          <p className="text-cyan-neon text-sm font-semibold tracking-widest uppercase mb-2">✦ Upload</p>
          <h1 className="text-4xl font-black text-white" style={{ fontFamily: 'Outfit' }}>Sell Your Artwork</h1>
          <p className="text-slate-400 mt-2">Share your creativity with the world and start earning</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Left - Upload */}
            <div className="space-y-6">
              {/* Dropzone */}
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-3">
                  Artwork Image <span className="text-red-400">*</span>
                </label>
                <div
                  {...getRootProps()}
                  className={`relative border-2 border-dashed rounded-2xl transition-all cursor-pointer overflow-hidden ${
                    isDragActive ? 'border-cyan-neon bg-cyan-neon/5' : 'border-white/15 hover:border-cyan-neon/40 hover:bg-white/3'
                  }`}
                  style={{ minHeight: '300px' }}
                >
                  <input {...getInputProps()} />

                  {preview ? (
                    <div className="relative">
                      <img src={preview} alt="Preview" className="w-full object-cover rounded-2xl" style={{ maxHeight: '360px' }} />
                      <div className="absolute inset-0 bg-black/50 opacity-0 hover:opacity-100 transition-all rounded-2xl flex items-center justify-center">
                        <p className="text-white font-semibold">Click to change</p>
                      </div>
                      <button
                        type="button"
                        onClick={(e) => { e.stopPropagation(); setPreview(null); setForm(p => ({ ...p, imageUrl: '' })); }}
                        className="absolute top-3 right-3 p-1.5 rounded-full bg-red-500/80 hover:bg-red-500 transition-all"
                      >
                        <X className="w-4 h-4 text-white" />
                      </button>
                      {uploading && (
                        <div className="absolute bottom-0 left-0 right-0 p-4 bg-black/70">
                          <div className="flex justify-between text-xs text-white mb-1">
                            <span>Uploading...</span><span>{uploadProgress}%</span>
                          </div>
                          <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
                            <div className="h-full bg-cyan-neon rounded-full transition-all" style={{ width: `${uploadProgress}%` }} />
                          </div>
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="absolute inset-0 flex flex-col items-center justify-center p-8 text-center">
                      <div className="w-16 h-16 rounded-2xl bg-cyan-neon/10 border border-cyan-neon/20 flex items-center justify-center mb-4">
                        <Upload className="w-8 h-8 text-cyan-neon" />
                      </div>
                      <p className="text-white font-semibold mb-1">
                        {isDragActive ? 'Drop your artwork here!' : 'Drag & drop your artwork'}
                      </p>
                      <p className="text-slate-400 text-sm mb-4">or click to browse files</p>
                      <p className="text-slate-500 text-xs">PNG, JPG, WEBP, GIF up to 50MB</p>
                    </div>
                  )}
                </div>
                {preview && (
                  <button
                    type="button"
                    onClick={handleAiGenerate}
                    disabled={analyzing || uploading}
                    className="w-full mt-4 py-3 px-4 rounded-xl border border-cyan-neon/30 bg-cyan-neon/10 hover:bg-cyan-neon/25 text-cyan-neon font-bold text-sm transition-all flex items-center justify-center gap-2 shadow-neon-sm disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {analyzing ? (
                      <>
                        <div className="w-4 h-4 rounded-full border-2 border-cyan-neon border-t-transparent animate-spin" />
                        Analyzing with Gemini 2.5 Flash...
                      </>
                    ) : (
                      <>✦ Auto-Generate Gallery Details (AI)</>
                    )}
                  </button>
                )}
              </div>


              {/* Price & License */}
              <div className="glass-card p-5 space-y-4">
                <h3 className="text-white font-semibold flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-cyan-neon" /> Pricing & License
                </h3>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1.5">
                    Price (₹) <span className="text-red-400">*</span>
                  </label>
                  <input
                    type="number"
                    value={form.price}
                    onChange={e => setForm(p => ({ ...p, price: e.target.value }))}
                    className="glass-input"
                    placeholder="e.g. 2499"
                    min="1"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">License Type</label>
                  <div className="space-y-2">
                    {LICENSE_TYPES.map(lic => (
                      <label
                        key={lic.value}
                        className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer transition-all ${
                          form.licenseType === lic.value ? 'border-cyan-neon/50 bg-cyan-neon/8' : 'border-white/10 hover:border-white/20'
                        }`}
                      >
                        <input
                          type="radio"
                          name="license"
                          value={lic.value}
                          checked={form.licenseType === lic.value}
                          onChange={e => setForm(p => ({ ...p, licenseType: e.target.value }))}
                          className="accent-cyan-400"
                        />
                        <div>
                          <p className="text-white font-medium text-sm">{lic.value}</p>
                          <p className="text-slate-400 text-xs">{lic.desc}</p>
                        </div>
                      </label>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Right - Details */}
            <div className="space-y-5">
              <div className="glass-card p-5 space-y-4">
                <h3 className="text-white font-semibold flex items-center gap-2">
                  <FileText className="w-4 h-4 text-cyan-neon" /> Artwork Details
                </h3>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1.5">
                    Title <span className="text-red-400">*</span>
                  </label>
                  <input
                    type="text"
                    value={form.title}
                    onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
                    className="glass-input"
                    placeholder="Give your artwork a captivating title"
                    maxLength={80}
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1.5">Description</label>
                  <textarea
                    value={form.description}
                    onChange={e => setForm(p => ({ ...p, description: e.target.value }))}
                    className="glass-input h-28 resize-none"
                    placeholder="Describe your artwork, inspiration, technique..."
                    maxLength={1000}
                  />
                  <p className="text-slate-500 text-xs mt-1">{form.description.length}/1000</p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1.5">
                    Category <span className="text-red-400">*</span>
                  </label>
                  <select
                    value={form.category}
                    onChange={e => setForm(p => ({ ...p, category: e.target.value }))}
                    className="glass-input"
                    required
                  >
                    <option value="" className="bg-navy">Select a category</option>
                    {CATEGORIES.map(cat => (
                      <option key={cat} value={cat} className="bg-navy">{cat}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1.5">Tags</label>
                  <div className="flex gap-2 mb-2">
                    <input
                      type="text"
                      value={tagInput}
                      onChange={e => setTagInput(e.target.value)}
                      onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addTag(); } }}
                      className="glass-input flex-1 text-sm"
                      placeholder="Add tags (press Enter)"
                    />
                    <button type="button" onClick={addTag} className="btn-outline text-sm py-2 px-4">Add</button>
                  </div>
                  {form.tags.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                      {form.tags.map(tag => (
                        <span key={tag} className="tag-pill flex items-center gap-1">
                          #{tag}
                          <button type="button" onClick={() => setForm(p => ({ ...p, tags: p.tags.filter(t => t !== tag) }))}>
                            <X className="w-3 h-3" />
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Tips */}
              <div className="glass-card p-5">
                <h3 className="text-white font-semibold text-sm mb-3 flex items-center gap-2">
                  <Shield className="w-4 h-4 text-cyan-neon" /> Tips for Success
                </h3>
                <ul className="space-y-2 text-sm text-slate-400">
                  <li className="flex items-start gap-2"><span className="text-cyan-neon mt-0.5">•</span> Use high-resolution images (min 2000×2000px)</li>
                  <li className="flex items-start gap-2"><span className="text-cyan-neon mt-0.5">•</span> Write a compelling title and description</li>
                  <li className="flex items-start gap-2"><span className="text-cyan-neon mt-0.5">•</span> Add relevant tags to improve discoverability</li>
                  <li className="flex items-start gap-2"><span className="text-cyan-neon mt-0.5">•</span> Price your work fairly based on complexity</li>
                </ul>
              </div>

              {/* Submit */}
              <button
                type="submit"
                disabled={submitting || uploading}
                className="btn-primary w-full py-4 text-base flex items-center justify-center gap-3 disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {submitting ? (
                  <><div className="w-5 h-5 rounded-full border-2 border-navy border-t-transparent animate-spin" /> Publishing...</>
                ) : (
                  <><Upload className="w-5 h-5" /> Publish Artwork</>
                )}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
